export const endpoints = {
  login: "/auth/login",
  me: "/auth/me",
  profile: "/auth/profile",
  changePassword: "/auth/change-password",
  departments: "/departments",
  forms: "/forms",
  reports: "/reports",
  reportsPublic: "/reports/public",
  reportsPerformance: "/reports/performance/latest",
  contracts: "/contracts",
  submissions: "/submissions",
  jiraMe: "/jira/me",
  jiraUsers: "/jira/users",
  jiraRequestTypes: "/jira/request-types",
};
