export const endpoints = {
  login: "/auth/login",
  logout: "/auth/logout",
  me: "/auth/me",
  profile: "/auth/profile",
  profileAvatar: "/auth/profile/avatar",
  changePassword: "/auth/change-password",
  chat: "/chat",
  departments: "/departments",
  banner: "/banner",
  pdfForms: "/pdf-forms",
  forms: "/forms",
  reports: "/reports",
  reportsPublic: "/reports/public",
  reportsPerformance: "/reports/performance/latest",
  contracts: "/contracts",
  submissions: "/submissions",
  userDashboard: "/user-dashboard",
  tasks: "/tasks",
  taskColleagues: "/tasks/colleagues",
  taskPendingCount: "/tasks/pending-count",
  taskUnseenCount: "/tasks/unseen-count",
  taskConversation: (submissionId: number) => `/submissions/${submissionId}/conversation`,
  taskComments: (submissionId: number) => `/submissions/${submissionId}/comments`,
  taskReminders: (submissionId: number) => `/submissions/${submissionId}/reminders`,
  jiraMe: "/jira/me",
  jiraUsers: "/jira/users",
  jiraRequestTypes: "/jira/request-types",
  adminDashboard: "/admin/dashboard",
  adminAnalytics: "/admin/analytics",
  adminUsers: "/admin/users",
  adminDepartments: "/admin/departments",
  adminFormAccessCatalog: "/admin/form-access/catalog",
  adminFormDuties: "/admin/form-duties",
  adminSessions: "/admin/sessions",
  adminBanner: "/admin/banner",
  adminNews: "/admin/news",
  adminPdfForms: "/admin/pdf-forms",
  news: "/news",
  managementLetters: "/management-letters",
  managementLetterRecipients: "/management-letters/recipients",
  managementLetterReport: "/management-letters/report",
  managementLetterAccess: "/management-letters/access",
  calendarEvents: "/calendar/events",
  calendarUsers: "/calendar/users",
  calendarNotifications: "/calendar/notifications/unread",
  calendarNotificationsRead: "/calendar/notifications/read",
};
