export const endpoints = {
  login: "/auth/login",
  logout: "/auth/logout",
  me: "/auth/me",
  profile: "/auth/profile",
  changePassword: "/auth/change-password",
  chat: "/chat",
  departments: "/departments",
  banner: "/banner",
  pdfForms: "/pdf-forms",
  forms: "/forms",
  reports: "/reports",
  reportsPublic: "/reports/public",
  reportsPerformance: "/reports/performance/latest",
  contracts: "/contracts",
  submissions: "/submissions",
  jiraMe: "/jira/me",
  jiraUsers: "/jira/users",
  jiraRequestTypes: "/jira/request-types",
  adminDashboard: "/admin/dashboard",
  adminUsers: "/admin/users",
  adminDepartments: "/admin/departments",
  adminFormAccessCatalog: "/admin/form-access/catalog",
  adminSessions: "/admin/sessions",
  adminBanner: "/admin/banner",
  adminPdfForms: "/admin/pdf-forms",
};
